 const APPLICATIONS_NAME:any = {
  Adverseevents:'aeWatch',
  AudioBooks:'AudioBooks',
  Automation:'Automation',
  AutoParts:'AutoParts',
  AutoPartsRA:'AutoPartsRA',
  Billing:'Billing',
  Brokers:'brokerWatch',
  Carrental:'Cars',
  Courts:'Courts',
  Cruises:'Cruises',
  Drug_watch:'ctWatch',
  cyberPrice:'cyberPrice',
  Drugs:'Drugs',
  Ferry:'Ferry',
  Financial:'Financial',
  airfare:'Flights',
  HomeGoods:'HomeGoods',
  HomeImprovement:'HomeImprovement',
  Hotel:'Hotels',
  Journal:'Journals',
  Newswatch:'newsWatch',
  RA:'RA',
  Rentmarketer:'Rental Entry',
  Rental_markets:'Rental Markets',
  Retail:'Retail',
  rollups:'Rollups',  
  Site_view:'siteWatch',
  Custom:'Solutions',
  Tires:'Tires',
  Vacation:'Vacations',
  }
  export default APPLICATIONS_NAME;